export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>

        <div className="p-4 text-center text-2xl">
          <h1>INNER layout</h1>
        </div>
        {children}
      </body>
    </html>
  );
}
