export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <div className="bg-green-600 p-4 text-center text-2xl">
          <h1>blogid layout</h1>
        </div>
      </body>
    </html>
  );
}
