export const metadata={
    title:"ABout Ujala",
    // title:{
    //     absolute:'About Ujala'
    // },
    description:"Generated by Ujala"
}

export  default function about(){
    return <h1>ABout page</h1>
}