"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";

// export const metadata = {
//   title: {
//     absolute: "login,register"
//   },
//   description: 'Generated by Next.js',
// };

const navLinks = [
  { name: "Register", href: "/register" },
  { name: "Login", href: "/login" },
  { name: "forgot-password", href: "/forgot-password" },
];
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const [state, setstate] = useState("");
  return (
    <main>
      <div>
        <input value={state} onChange={(e) => setstate(e.target.value)} className="text-red-500" />
      </div>
      {navLinks.map((link) => {
        const isActive = pathname === link.href;
        return (
          <Link
            href={link.href} 
            key={link.name}
            className={isActive ? " text-sky-300 ml-4" : "ml-4"}
          >
            {link.name}
          </Link>
        );
      })}
      {children}
    </main>
  );
}
